Document: musikernel3
Title: Debian musikernel3 Manual
Author: <insert document author here>
Abstract: This manual describes what musikernel3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/musikernel3/musikernel3.sgml.gz

Format: postscript
Files: /usr/share/doc/musikernel3/musikernel3.ps.gz

Format: text
Files: /usr/share/doc/musikernel3/musikernel3.text.gz

Format: HTML
Index: /usr/share/doc/musikernel3/html/index.html
Files: /usr/share/doc/musikernel3/html/*.html
